### PR TITLE
vSphere ubuntu

### PR DESCRIPTION
**Pull request by chaospuppy**
Adds an RKE2 build on top of Ubuntu for vSphere.  Also includes a small fix to resolve a race condition that was causing the pipeline to fail (retries for rke2-install.sh provisioning).

### CODE REVIEW

**Review by mjnagel — DISMISSED** [review]
Might be worth setting up codeowners here for some of the subdirectories. In particular might be something like:
- `packer/vsphere`: owned by @chaospuppy n company (@defenseunicorns/mission-ops-team ?)
- `packer/nutanix`: owned by @jacobbmay n company (@defenseunicorns/digital-salmon ?)
- _all_ other files: owned by @defenseunicorns/uds-core 

Given the current limited ability to CI test vsphere/nutanix it's probably good to have those owned by teams that have access to test environments. Also could adjust CI accordingly so that the AWS CI isn't required when only vsphere/nutanix changes are present.

**Comment by chaospuppy** [comment]
Issue created to get Codeowners in place 🚀

**Review by mjnagel — APPROVED** [review]

**Pull request merged**
